sudo: required
dist: trusty
language: generic
install: bash -ex ./.travis-install.sh
script: bash -ex ./.travis-script.sh
cache:
  directories:
    - /usr/local

env:
  - PACKAGE=mathopd
  - PACKAGE=hiawatha

# Touch me to force a build 1
