sudo: required
dist: trusty
language: generic
install: bash -ex ./.travis-install.sh
script: bash -ex ./.travis-script.sh

env:
  - PACKAGE=mathopd
  - PACKAGE=hiawatha

# Touch me to force a build 1
